### ISSUE TITLE
"Run local tests" not lighting up

### ISSUE THREAD

**Issue by ChiselD** [learn-co-curriculum/swift-HelloToTheUniverse-lab#10]

**Comment by ChiselD** [comment]
Despite tests passing successfully (it appears) on my local computer, the second of the three success lights in the first lesson is not illuminated.

**Comment by JimCampagno** [comment]
I had just updated this this morning, you might not have my most recent version.

When did you clone this lab down to begin working on it?

@ChiselD

**Comment by ChiselD** [comment]
Hi Jim, thanks for your reply! I cloned it only about two hours ago, so I think I ought to have the right version. Is there a way to delete my copy of the project entirely and try that lesson over again from the top?

**Comment by JimCampagno** [comment]
Yea. Go to your copy (on your Github) and then hit settings and Delete this repository. Then delete locally from your computer... THEN go back and re-fork the lab and re-clone it down to your machine. The solution is included in the project so you should only have to hit command + u to run the tests and you should be fine.

Let me know if that works.

@ChiselD

**Comment by ChiselD** [comment]
![screen shot 2016-09-14 at 5 10 22 pm](https://cloud.githubusercontent.com/assets/3756776/18530150/2b99cfba-7a9e-11e6-978a-876c01aec6ac.png)

OK, I deleted from both places in the suggested order, went back to the main learn.co Github and found the repo in question and forked from there to my own page. So far, so good. However, when I tried to clone using Terminal, I got this error message (see screenshot). Any advice? Should I create a new folder for this lab first before attempting to clone down?

**Comment by ChiselD** [comment]
(Forgot to mention, as far as I know I have indeed established an SSH before. My understanding was that that is a one-time process that doesn't need to be repeated.)

**Comment by JimCampagno** [comment]
You need to make sure you fork the lab before cloning.

@ChiselD

**Comment by ChiselD** [comment]
Yup, I'm pretty sure I did that correctly (see attached screenshot – this shows the screen from which I clicked "Clone or download").

![screen shot 2016-09-14 at 5 52 53 pm](https://cloud.githubusercontent.com/assets/3756776/18531423/42835b82-7aa4-11e6-9efb-f042fa611a8a.png)

I guess I can probably just clone with HTTPS if I have to... (wish the SSH would work, though)

**Comment by JimCampagno** [comment]
Interesting. I'm curious if the SSH doesn't work on other labs. I would move forward for now and then see if the SSH key problem comes up in a future lab.

@ChiselD

**Comment by ChiselD** [comment]
Yeah, it didn't work with the next one (Playgrounds: Printing and String Interpolation) either, so I'm just using HTTPS for that one and moving forward. I'll look up ways to check the validity of my established SSH key later... just wanted to report in.

Thanks in any case @JimCampagno for being so responsive! Enjoying the course so far.

**Comment by JimCampagno** [comment]
Great to hear! Yea.. look at ways to re-setup your SSH key. It seems like it's a GitHub issue. Good luck on your journey, the trick is to keep at it!

@ChiselD
