### ISSUE TITLE
Run Local Tests

### ISSUE THREAD

**Issue by JimmyBrown** [learn-co-curriculum/swift-HelloToTheUniverse-lab#11]
All my tests succeed but the green light doesn't light up n the learn.co website.

**Comment by JimCampagno** [comment]
Hey Jimmy! I had just made changes to this particular lab to fix that problem. 

There are ways for you to go back and make the light come up for this lab... OR (what I recommend) is that you continue to move forward and ignore the green light for this one lab (for now).

@JimmyBrown
