### ISSUE TITLE
Swift 3 conversion

### ISSUE THREAD

**Issue by jobedutate1026** [learn-co-curriculum/swift-HelloToTheUniverse-lab#14]
I don't know if I did it correctly but if you convert to swift 3 the test will not pass.

**Comment by JimCampagno** [comment]
I had updated the lab to work with Swift 3 and the latest Xcode version. When did you fork and clone down the lab. I updated this lab yesterday (an update that you might not see depending on when you cloned the lab down).

Based upon your response, I can have you do something else. To be honest, I think it's best for you to move forward and continue learning! There are labs coming up that have tests as well, if you see problems where the lights don't light up on those--raise an issue and I'll jump in to help you out.

@jobedutate1026
