### ISSUE TITLE
Issue with git push

### ISSUE THREAD

**Issue by JoumanaE** [learn-co-curriculum/swift-HelloToTheUniverse-lab#16]
Hello, 

I am trying to "git push" the hello to the universe lab, but I receive the following error message: 

Permission to learn-co-students/swift-HelloToTheUniverse-lab-swift-intro-000.git denied to JoumanaE.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I am not sure why.

**Comment by JimCampagno** [comment]
Hey! So you need to first fork the lab _then_ clone it to your computer. It appears you cloned down the lab before forking (which would give you your own copy) before cloning it down. Watch the video I have to see how I went about doing that.

For now, you can continue to move forward--just make sure when you reach a lesson that's a lab, that you fork the lab before you clone it down.

@JoumanaE

**Comment by JoumanaE** [comment]
![screen shot 2016-09-15 at 12 29 00 pm](https://cloud.githubusercontent.com/assets/10995880/18559640/30a6e0c6-7b46-11e6-8781-d35d44f42d8b.png)
This is the message I get. I am pretty sure I forked it. I tried deleting my local copy and forking it again. I get the same message.

**Comment by JimCampagno** [comment]
Hey @JoumanaE --did this get resolved?
