### ISSUE TITLE
run local test light

### ISSUE THREAD

**Issue by denzalvin** [learn-co-curriculum/swift-HelloToTheUniverse-lab#18]
Good day.

I followed step by step of your video but the run local test did not turn green. When I tried ignoring it, and clicked on the next lesson, I got a message telling me to complete in sequence. Did I miss a step or two, that may not be in your youtube instruction so the light will turn green?

**Comment by JimCampagno** [comment]
I've added some instructions to the welcome lab that includes setting up an SSH key. Go through those instructions [here](https://github.com/learn-co-students/swift-welcome-swift-intro-000).

After going through those instructions again, let me know if you're still unable to get the light to turn green.

@denzalvin

**Comment by JimCampagno** [comment]
Run this command in terminal:

`bash <(curl -s https://raw.githubusercontent.com/flatiron-school/ios-setup/master/install.sh)`

After doing that, try again, refresh your browser and let me know if it works!

@denzalvin
