### ISSUE TITLE
Local Test / Workspace folder

### ISSUE THREAD

**Issue by MyloTuT** [learn-co-curriculum/swift-HelloToTheUniverse-lab#19]
My local test light is not lighting up. Also when I cloned the git repo, I didn't receive the workspace file so I had to work off the project file.

**Comment by JimCampagno** [comment]
Hey! I had updated the welcome page with detailed instructions that you should check out [here](https://github.com/learn-co-curriculum/swift-welcome)

As well, you're correct--you should use the .xcodeproj file. I had just updated the video to reflect that now!

@MyloTuT

**Comment by JimCampagno** [comment]
Run this command in terminal:

`bash <(curl -s https://raw.githubusercontent.com/flatiron-school/ios-setup/master/install.sh)`

After doing that, try again, refresh your browser and let me know if it works!

@MyloTuT

**Comment by AnnJohn** [comment]
hi @MyloTuT please let us know if you were able to get this to work with the above instructions. thanks
