### ISSUE TITLE
No green light on the run Local Tests

### ISSUE THREAD

**Issue by jamiedf76** [learn-co-curriculum/swift-HelloToTheUniverse-lab#20]
I have gone through each of the steps in the Welcome Reading lesson a second time to make sure I have not missed anything and I have forked the lab ok and get the green light for that. 

The test ran fine in my xcode but I am getting no green light for run local test.

**Comment by JimCampagno** [comment]
Run this command in terminal:

`bash <(curl -s https://raw.githubusercontent.com/flatiron-school/ios-setup/master/install.sh)`

After doing that, try again, refresh your browser and let me know if it works!

@jamiedf76

**Comment by AnnJohn** [comment]
@jamiedf76 did this resolve the issue? thanks
