### ISSUE TITLE
I couldn't get the local test to be green

### ISSUE THREAD

**Issue by M-KH** [learn-co-curriculum/swift-HelloToTheUniverse-lab#21]
Hi 
I got the test done and everything seems fine. Test was succeeded but I still did not get the green light for the local test I don't know what is the problem.

I got the green light for submitting the lab.

Thank you

**Comment by JimCampagno** [comment]
Run this command in terminal:

`bash <(curl -s https://raw.githubusercontent.com/flatiron-school/ios-setup/master/install.sh)`

After doing that, try again, refresh your browser and let me know if it works!

@M-KH

**Comment by M-KH** [comment]
It's green now! 
thank you
