### ISSUE TITLE
Include install.sh instructions on README

### ISSUE THREAD

**Issue by ianrahman** [learn-co-curriculum/swift-HelloToTheUniverse-lab#3]
The following line is included on the Detail.md, but is necessary for green light functionality and should be included on the README.md.
`bash <(curl -s https://raw.githubusercontent.com/flatiron-school/ios-setup/master/install.sh)`

**Comment by JimCampagno** [comment]
Awesome stuff Mr. Rahman. Thank you for this.

@ianrahman
