### ISSUE TITLE
Forked Over Project.. Learn not lighting up 

### ISSUE THREAD

**Issue by apena143** [learn-co-curriculum/swift-HelloToTheUniverse-lab#8]
As above, I forked over the project and its on my desktop and its in my github account, buuut the light just isn't registering. 
Also I don't have an SSH, so I just used the HTTPS to clone the file. My terminal didn't prompt me for a username and password and downloaded the project fine. If I did try to download it with SSH(yeah, I tried just to see), it was denied. I don't know if that is anything that needs addressing, just thought I should mention it.

**Comment by JimCampagno** [comment]
@apena143 This should now be fixed. As well, this particular lab has been upgraded to work with Xcode 8.0 and Swift 3.0. You can update our Xcode via the Mac App store if you haven't already.

Let me know if that solves your problem.
