### ISSUE TITLE
Local test

### ISSUE THREAD

**Issue by marcowright** [learn-co-curriculum/swift-HelloToTheUniverse-lab#9]
The light is not lighting up after the test pass locally.

**Comment by JimCampagno** [comment]
When you go to your version on GitHub, how many commits do you see? 

![](http://i.imgur.com/ZxRvTJQ.png)

Do you see 30 commits? If not, how many?

**Comment by marcowright** [comment]
I see 24 commits.

**Comment by JimCampagno** [comment]
Ok. There are a few ways to do this (but lets take the easy way out).

If you locate your forked version of the lab, hit settings then delete your lab permanently. Also, delete the lab from your computer as well.

After doing that, re-fork the lab as that will include all the changes I just made this morning. Let me know if you have any trouble with that.

**Comment by marcowright** [comment]
Thanks Jim. The commit went well. There were no conflicts this time.
Unfortunately, the build failed due to Use of Undeclared type of "
UIApplicationLaunchOptionsKey".

**Comment by JimCampagno** [comment]
What version of Xcode are you running?

@marcowright

**Comment by JimCampagno** [comment]
Marco, I'm closing this issue. Feel free to open up another one if you're having trouble. You need to update your Xcode to Xcode 8 (which can be done in the Mac App Store.)

@marcowright
